import React from 'react';
import Icon from './icon.js';

function Play(props){
	return (
		<Icon {...props}>
		//Generated by IcoMoon.io 
			<title>{props.title}</title>
			<path d="M6 4l20 12-20 12z"></path>
		</Icon>
	)
}
export default Play;