import React from 'react';
import Icon from './icon.js';

function Pause(props){
	return (
		<Icon {...props}>
		//Generated by IcoMoon.io 
			<title>{props.title}</title>
			<path d="M4 4h10v24h-10zM18 4h10v24h-10z"></path>
		</Icon>
	)
}
export default Pause;